# Default config:
[API]
 ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
#  RemoteListenAddress = ""
#  Timeout = "30s"
#
[Libp2p]
 ListenAddresses = ["/ip4/0.0.0.0/tcp/22662", "/ip6/::/tcp/0"]
#  AnnounceAddresses = []
#  NoAnnounceAddresses = []
#  BootstrapPeers = []
#  ProtectedPeers = []
#  BlacklistPeers = []
#  WhitelistPeers = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
  #  DirectPeers = ["/ip4/192.168.1.142/tcp/44741/p2p/12D3KooWMGepf9rvEsuUyznRebT7f7fhBq2DD6oVvct1CkWZWYtU"]

 DirectPeers = ["12D3KooWMGepf9rvEsuUyznRebT7f7fhBq2DD6oVvct1CkWZWYtU"]#
[ServerApi]
#  EndPoint = ""
#
[MessageApi]
#  EndPoint = ""
#
[Client]
#  UseIpfs = false
#  IpfsMAddr = ""
#  IpfsUseForRetrieval = false
#
[Metrics]
#  Nickname = ""
#  HeadNotifs = false
#

[RPCServer]
 ServerUrls = ["http://127.0.0.1:1234/rpc/v0","88888"]